config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: "custom_sessions", omniauth_callbacks: "callbacks" }
  devise_scope :user do
    resources :users, only: [ :show, :index ] do
      member do
        get :following, :followers
      end
    end
  end

  scope module: :web do
    root 'home#index'
    resources :movies do
      resources :comments
      get 'recommendations', on: :member
    end
    resource :votes, only: :update
    resources :reviews do
      resources :comments
    end
    resources :relationships, only: [ :create, :destroy ]
  end
end

app/controllers/web/movies_controller.rb
# frozen_string_literal: true

module Web
  # Movies controller
  class MoviesController < Web::BaseController
    before_action :find_movie, except: :index
    respond_to :js, :html, only: :show

    def index
      movies = FindMovies.new(Movie.all, current_user).call(movie_params).distinct
      message = FindMoviesMessage.message(movie_params)
      render :index, locals: { movies: movies, message: message }
    end

    def show
      id = @movie.id
      review = Review.where(movie_id: id, user_id: current_user)
      comments = @movie.comments.order(:created_at).all
      vote = Vote.find_by(user_id: current_user, movie_id: id)
      render :show, locals: { review: review, comments: comments, vote: vote }
    end

    def recommendations
      @recommendations = Movie.where(tmdb_id: @movie.recommendations)
    end

    private

    def movie_params
      params.permit(:recommendation, :page, :current_user, :search, :genres, :sort, :order)
    end

    def find_movie
      @movie = @commentable = MoviePresenter.new(Movie.find(params[:id]))
    end
  end
end

app/views/web/movies/_movie.html.slim
.row
  .text-center.col-md-3.col-lg-2
    = link_to(movie) do
      = image_tag(present(movie).poster_path('w300'), height: '200')
    br/
    = movie.vote_average
  .col-md-9.col-lg-10
    strong
      = link_to present(movie).title_year, movie
    br/  
    = movie.overview
br/

app/views/web/movies/index.html.slim
.container
  = form_with url: '/movies', method: :get, local: true, class: "form-inline" do |form|
    = form.label :recommendation, 'Status:'
    = form.select :recommendation, ["Recommended", "Not recommended", "Neutral", "Not evaluated"], { include_blank: true }, { class: "form-control" }
    = form.label :search, 'Text:'  
    = form.text_field :search, class: "form-control"
    = form.label :genres, 'Genre:'   
    = form.select :genres, ["Action", "Adventure", "History", "War", "Comedy", "Drama", "Romance", "Horror", "Thriller", "Science Fiction", "Mystery", "Fantasy", "Crime", "Family", "Animation", "Western", "Music", "Foreign"], { include_blank: true }, { class: "form-control" }
    = form.radio_button(:sort, 'Rating', id: 'rating')
    = form.label 'Rating'    
    = form.radio_button(:sort, 'Date', id: 'date')
    = form.label 'Date'
    = form.check_box :order
    = form.label :order, "Reverse"
    = form.submit "Search/reorder", class: "btn btn-default btn-primary"
br/
h5 Results for: #{message} (#{movies.total_count}).
br/
= paginate movies, theme: 'twitter-bootstrap-4'
= render movies
= paginate movies, theme: 'twitter-bootstrap-4'

app/views/web/movies/recommendations.html.slim
h5.my-4.text-center
  | Recommendations from TMDB for: 
  = link_to @movie.title, @movie
.row.text-center
  - @recommendations.each do |rec_movie|
    .col-lg-3.col-md-4.col-xs-12.text-center
      a.d-block.mb-4.h-105
        = link_to present(rec_movie).short_title, rec_movie
        br/
        = link_to(rec_movie) do
          = image_tag(present(rec_movie).poster_path('w92'))
        br/
        = rec_movie.vote_average
        hr/

app/views/web/movies/show.html.slim
.row
  .col-lg-4.col-md-5.text-center
    = image_tag(@movie.poster_path('w300'), height: '380')
  .col-lg-8.col-md-7
    h4.text-center
      = @movie.title_year
    br/
    = @movie.overview
    br/
    = @movie.rating_title
    br/
    = link_to "On IMBD ", "http://www.imdb.com/title/#{@movie.imbd_id}/"
    = @movie.vote_average
    br/
    | Genres:
    - @movie.genres.each do |genre|
      =< link_to "#{genre}  ", movies_path(genres: genre)
    br/
    = link_to "Recommendations from TMDB", recommendations_movie_path(@movie)
    br/
    = @movie.my_review_link(review)
    br/
    = @movie.all_review_link
    #rec
      = @movie.recommendation(vote)
    | Change to:
    =< link_to 'recommended', votes_path(value: 1, movie_id: @movie), remote: true, method: :patch, id: 'recommended'
    =< link_to 'neutral', votes_path(value: 0, movie_id: @movie), remote: true, method: :patch, id: 'neutral'
    =< link_to 'not recommended', votes_path(value: -1, movie_id: @movie), remote: true, method: :patch, id: 'not-recommended'
br/
= render comments
#comments
= link_to 'New comment', new_movie_comment_path(@movie), remote: true, class: 'float-right'
br/
= link_to 'Close comment form', '#', id: 'comment-close', remote: true, class: 'float-right'
#form-comment