config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: "custom_sessions", omniauth_callbacks: "callbacks" }
  devise_scope :user do
    resources :users, only: [ :show, :index ] do
      member do
        get :following, :followers
      end
    end
  end

  scope module: :web do
    root 'home#index'
    resources :movies do
      resources :comments
      get 'recommendations', on: :member
    end
    resource :votes, only: :update
    resources :reviews do
      resources :comments
    end
    resources :relationships, only: [ :create, :destroy ]
  end
end

app/models/user.rb
# frozen_string_literal: true

# :reek:DuplicateMethodCall { exclude: [ from_omniauth ]

# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :votes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  validates :username,  presence: true
  mount_uploader :avatar, AvatarUploader

  delegate :count, to: :following, prefix: true
  delegate :count, to: :followers, prefix: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def followings?(other_user)
    following.include?(other_user)
  end
end

app/models/user/guest_user.rb
# frozen_string_literal: true

# :reek:Attribute { exclude: [ :email, :username, :role ]

class GuestUser < User
  attr_accessor :email, :username, :role
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users and followers/followings controler
class UsersController < ApplicationController
  before_action :find_user, except: :index

  def show
    @followed = current_user.active_relationships.find_by(followed_id: @user.id)
  end

  def index
    @users = User.all.order(:created_at).page(params[:page]).per(10)
  end

  def following
    @users = @user.following.order(:created_at).page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    @users = @user.followers.order(:created_at).page(params[:page]).per(10)
    render 'show_follow'
  end

  private

  def find_user
    @user = UserPresenter.new(User.find(params[:id]))
  end
end

app/views/users/_follow.html.slim
= form_with model: current_user.active_relationships.build do |form|
  = hidden_field_tag :followed_id, @user.id
  = form.submit "Follow", class: "btn btn-default btn-primary"

app/views/users/_profile.html.slim
= current_user.email

app/views/users/_unfollow.html.slim
= form_with model: @followed, html: { method: :delete } do |form|
  = form.submit 'Unfollow', class: "btn btn-default btn-primary"

app/views/users/_user.html.slim
.container
  .row
    .text-center.col-md-4.col-lg-3
      = link_to "#{user.username}", user, id: user.id
      br/
      = link_to(user) do
        = image_tag(user.avatar.url, height: '60', class: "rounded-circle")
    .col-md-8.col-lg-9
      = user.about
      hr/
      = present(user).reviews_votes
br/

app/views/users/index.html.slim
= paginate @users, theme: 'twitter-bootstrap-4'
= render partial: 'users/user', collection: @users
= paginate @users, theme: 'twitter-bootstrap-4'

app/views/users/show.html.slim
| Name: #{@user.username} #{image_tag(@user.avatar.url, height: '40', class: "rounded-circle")}
br/
| Registration: #{@user.created_at}
br/
| About me: #{@user.about}
br/
= link_to_if(@user.following_count > 0, "following #{@user.following_count}", following_user_path(@user))
br/
= link_to_if(@user.followers_count > 0, "followers #{@user.followers_count}", followers_user_path(@user))
br/
= render "#{@user.action(current_user)}"

app/views/users/show_follow.html.slim
= paginate @users, theme: 'twitter-bootstrap-4'
= render partial: 'users/user', collection: @users
= paginate @users, theme: 'twitter-bootstrap-4'