config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: "custom_sessions", omniauth_callbacks: "callbacks" }
  devise_scope :user do
    resources :users, only: [ :show, :index ] do
      member do
        get :following, :followers
      end
    end
  end

  scope module: :web do
    root 'home#index'
    resources :movies do
      resources :comments
      get 'recommendations', on: :member
    end
    resource :votes, only: :update
    resources :reviews do
      resources :comments
    end
    resources :relationships, only: [ :create, :destroy ]
  end
end

app/controllers/web/reviews_controller.rb
# frozen_string_literal: true

# :reek:NilCheck { exclude: [ find_movie ] }

module Web
  # Reviews of users controller
  class ReviewsController < Web::BaseController
    before_action :find_review, except: %i[index new create]
    before_action :find_movie

    def index
      @reviews = @movie.reviews.includes(:user).order(:created_at).page(params[:page]).per(10)
      redirect_to @movie if @reviews.empty?
    end

    def show
      @commentable = @review
      comments = @review.comments.order(:created_at).all if @review
      render :show, locals: { comments: comments }
    end

    def new
      @review = Review.new
    end

    def edit; end

    def create
      @review = Review.new(review_params.merge(user: current_user))
      if @review.save
        redirect_to @review
      else
        render :new
      end
    end

    def update
      if @review.update(review_params)
        redirect_to @review
      else
        render :edit
      end
    end

    def destroy
      @review.destroy
      redirect_to reviews_path(movie_id: @movie.id)
    end

    private

    def review_params
      params.require(:review).permit(:movie_id, :text)
    end

    def find_review
      review = Review.find_by(id: params[:id]) || Review.where(user: current_user, movie_id: params[:movie_id]).first
      @review = ReviewPresenter.new(review)
    end

    def find_movie
      @movie = @review&.movie || Movie.find_by(id: params[:movie_id])
    end
  end
end

app/views/reviews/_form.html.slim
= render 'movies/movie', movie: @movie
= form_with model: @review, local: true, :html => {:class => "form-horizontal center"} do |f|
  .form-group
    = f.label :text, "My review:"
    = f.trix_editor :text, style: "overflow-y: auto;"
    = f.hidden_field :movie_id, value: params[:movie_id]
  .form-group
  = f.submit "Submit", class: "btn btn-default btn-primary"
= link_to 'Back', reviews_path(movie_id: params[:movie_id])

app/views/reviews/show.html.slim
= render 'movies/movie', movie: @movie
- if @review.user == current_user
  strong My review
- else
  strong Review of #{@review.user.username}
= sanitize @review.text, tags: %w(strong em p br div ul ol li)
= link_to 'All reviews', reviews_path(movie_id: @movie.id)
- if @review.user == current_user
  =< link_to 'Edit review', edit_review_path(@review, movie_id: @movie.id)
  =< link_to 'Destroy', review_path(@review), method: :delete, data: { confirm: 'Are you sure?' }
hr/
= render @comments if @comments
#comments
= link_to 'New comment', new_review_comment_path(@review), remote: true, class: 'float-right'
br/
= link_to 'Close comment form', '#', id: 'comment-close', remote: true, class: 'float-right'
#form-comment